# Utilisation d'une image Node.js comme base
FROM node:14 AS builder

# Répertoire de travail
WORKDIR /app

# Copie du fichier package.json et package-lock.json
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie de l'application Angular dans le conteneur
COPY . .

# Build de l'application Angular
RUN ng build --prod

# Deuxième étape, à partir d'une image Nginx pour servir l'application Angular
FROM nginx:1.20

# Copie des fichiers de build d'Angular dans le répertoire de Nginx
COPY --from=builder /app/dist/* /usr/share/nginx/html/

# Configuration du port d'écoute d'Nginx
EXPOSE 80

# Commande pour démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
